site_name: Notes
site_url: https://notes.shanakadesoysa.com/
site_author: Shanaka C. DeSoysa
repo_url: https://github.com/shanaka-desoysa/notes/
docs_dir: docs/
edit_uri: blob/main/docs/
theme:
  name: material
  # custom_dir: overrides
  icon:
    logo: material/note
# theme:
#     name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
markdown_extensions:
  - meta
  - attr_list
  - codehilite
  - admonition
  - footnotes
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

# nav:
# - Home: index.md
# - Notebook: notebooks/notebook.ipynb

plugins:
  - search
  - mknotebooks

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/shanakadesoysa
    - icon: fontawesome/brands/github 
      link: https://github.com/shanaka-desoysa
  analytics:
    provider: google
    property: G-FQ0JJJ0W06
