site_name: Notes
site_url: https://shanaka-desoysa.github.io/short-notes/
site_author: Shanaka C. DeSoysa
repo_url: https://github.com/shanaka-desoysa/short-notes/
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/note
# theme:
#     name: readthedocs
  highlightjs: true
  hljs_languages:
    - python
markdown_extensions:
  - meta
  - attr_list
  - codehilite
  - admonition
  - footnotes
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

# nav:
# - Home: index.md
# - Notebook: notebooks/notebook.ipynb

plugins:
  - search
  - mknotebooks
google_analytics:
  - UA-135532366-2
  - auto